// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMltQa6NaT2-EJ3JfA13VPoMixshNcjEo',
    appId: '1:733849395047:web:e0c17b10c336a79d1dd9c2',
    messagingSenderId: '733849395047',
    projectId: 'peereess',
    authDomain: 'peereess.firebaseapp.com',
    storageBucket: 'peereess.firebasestorage.app',
    measurementId: 'G-1K1982PCZX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7v94TR2xpibWN1-_xkdGoJQ1zFr1hjCc',
    appId: '1:733849395047:ios:14c34022b1af5e591dd9c2',
    messagingSenderId: '733849395047',
    projectId: 'peereess',
    storageBucket: 'peereess.firebasestorage.app',
    iosBundleId: 'com.example.peereess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFKe91kQzyfQwX9aD2sUXj3OAzQtWDrEw',
    appId: '1:733849395047:web:fb0a859a40ed24cd1dd9c2',
    messagingSenderId: '733849395047',
    projectId: 'peereess',
    authDomain: 'peereess.firebaseapp.com',
    storageBucket: 'peereess.firebasestorage.app',
    measurementId: 'G-B5PJT60VF5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7v94TR2xpibWN1-_xkdGoJQ1zFr1hjCc',
    appId: '1:733849395047:ios:14c34022b1af5e591dd9c2',
    messagingSenderId: '733849395047',
    projectId: 'peereess',
    storageBucket: 'peereess.firebasestorage.app',
    iosBundleId: 'com.example.peereess',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5-CSVvaimEMWzIn2T_ZPJftT6XnZcke8',
    appId: '1:733849395047:android:ae96a5687c8c131e1dd9c2',
    messagingSenderId: '733849395047',
    projectId: 'peereess',
    storageBucket: 'peereess.firebasestorage.app',
  );

}